# The services of the project.
#
# Each service listed will be deployed to power your project.

mysql:
    type: mysql:10.4
    disk: 2048

redis:
    type: redis:5.0

elasticsearch:
    type: elasticsearch:7.7
    disk: 1024
    configuration:
        plugins:
            - analysis-icu
            - analysis-phonetic

rabbitmq:
    type: rabbitmq:3.5
    disk: 1024
